### PR TITLE
Speeding up IAPWS97 with Numpy (2x to 20x improvement)

### PR DESCRIPTION
**Pull request by ellieLitwack**
¡Hola!

Hope you are well and happy new year. I've gone through IAPWS97 and switched most of the big array operations to NumPy.

This speeds up many of the functions in IAPWS97.

As an example, the percall time (non-cumulative) for _Region2 has gone from 1800 microseconds to 90 microseconds. _Backward3x_v_PT has gone from 116 microseconds to 44. Running test.py went from 17.7 seconds to 6.25 seconds for me.

I would say that I've done all of the easy ones (the other functions require more refactoring to vectorize - _txx_P, for example, require changing ng from a dictionary to a series of if statements as I did for _deriv_G). More could be done to improve the those functions.

### CODE REVIEW

**Comment by jjgomera** [comment]
Great idea, but is it necessary extract the array of procedures and thicken the namespace of module with the array parameters?

**Comment by ellieLitwack** [comment]
Unfortunately declaring the arrays outside of the functions it is necessary. Creating a numpy object is relatively expensive. I tried moving the arrays back into the Region2 function and got 674 microseconds per function call, so still an improvement over baseline but not as good as having the arrays defined outside of the function.

I agree that having all those constants in iapws97.py is not so nice. What about putting them in their own file, which has no impact on performance? I updated the PR with that edit.

**Comment by jjgomera** [comment]
Ok, Merged, I would like edit the namespace but now I have no time.

I'm talking about easy reading style like [here](https://github.com/jjgomera/iapws/pull/66/commits/630effb6190d659676f30abbeef7fc5f96785936#diff-81f34c145c117953aec4bc3edd85116c1b2be8617dd8d11b2ab873979a5f54ddL782), this speed-up really break the [pythonic style](https://docs.python-guide.org/writing/style/) as I do understand it, anyway applied.

Thank you for your contribution, 
Saludos amigo/a jeje

**Comment by ellieLitwack** [comment]
Hi - thanks for the feedback. No rush to answer as I understand you are busy, but I did want to make sure I fully understand the best style to use. I plan to make additional contributions to help speed up this package (specifically targeting humidAir as that is one I use frequently), so I want to write those contributions in the best style possible.

I'd also be happy to rewrite this most recent contribution.

I think I understand what was wrong with commit [b11fa83](https://github.com/jjgomera/iapws/pull/66/commits/b11fa83181a50b9308e160ec74a24ac4637fc7f1). As I understand it, that commit introduced to many variables into one namespace and made the file difficult to read.

What I don't understand is how I could improve [767b2af](https://github.com/jjgomera/iapws/pull/66/commits/767b2afceb2863235b466bc221152bfe61ab27ab).

Thank you for any advice you are able to give!

**Pull request merged**
